[pytest]
addopts = --verbose --cov=nodestream --tb=long --cov-report=html:build/reports/html --cov-report=xml:build/reports/coverage.xml --cov-report=term-missing --junitxml=build/reports/junit.xml  --disable-warnings
testpaths = tests
