- implementation: nodestream.extractors:FileExtractor
  arguments:
    globs:
      - people/*.json

- implementation: nodestream.interpreting:Interpreter
  arguments:
    interpretations:
      - type: source_node
        node_type: Person
        key:
          first_name: !jmespath firstName
          last_name: !jmespath lastName
        properties:
          age: !jmespath age
      - type: relationship
        node_type: Person
        relationship_type: KNOWS
        node_key:
          first_name: !jmespath friends[*].firstName
          last_name: !jmespath friends[*].lastName
        find_many: true

- implementation: nodestream.databases:GraphDatabaseWriter
  arguments:
    batch_size: 1000
    database: neo4j
    uri: bolt://localhost:7687
    username: neo4j
    password: neo4j123
