- implementation: nodestream.pipeline:IterableExtractor
  factory: range
  arguments:
    stop: 100000

- implementation: nodestream.interpreting:Interpreter
  arguments:
    interpretations:
      - type: source_node
        node_type: Number
        key:
          number: !jmespath index

- implementation: nodestream.databases:GraphDatabaseWriter
  arguments:
    batch_size: 1000
    database: !config neo4j_database
    uri: !config neo4j_uri
    username: !config neo4j_username
    password: !config neo4j_password
